# Generated by Django 3.2.2 on 2021-07-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commented',
            name='parent',
        ),
    ]
