# Generated by Django 3.2.2 on 2021-07-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_commented_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commented',
            name='timestamp',
        ),
    ]
