# Generated by Django 3.2.2 on 2021-07-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_commented_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commented',
        ),
    ]
